return {
	width = 29,
	height = 29,
	startLocation = { x = 14, y = 22 },
	ground = {
		[6] = {
			[8] = { texture = 'beach-tl', rotation = 0 },
			[9] = { texture = 'beach-tm', rotation = 0 },
			[10] = { texture = 'beach-tm', rotation = 0 },
			[11] = { texture = 'beach-tm', rotation = 0 },
			[12] = { texture = 'beach-tm', rotation = 0 },
			[13] = { texture = 'beach-tm', rotation = 0 },
			[14] = { texture = 'beach-tm', rotation = 0 },
			[15] = { texture = 'beach-tm', rotation = 0 },
			[16] = { texture = 'beach-tm', rotation = 0 },
			[17] = { texture = 'beach-tr', rotation = 0 }
		},
		[7] = {
			[8] = { texture = 'beach-lm', rotation = 0 },
			[9] = { texture = 'grass', rotation = 0 },
			[10] = { texture = 'grass', rotation = 0 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'grass', rotation = 0 },
			[17] = { texture = 'beach-dn', rotation = 0 },
			[18] = { texture = 'beach-tr', rotation = 0 },
			[19] = { texture = 'beach-tl', rotation = 0 },
			[20] = { texture = 'beach-tm', rotation = 0 },
			[21] = { texture = 'beach-tm', rotation = 0 },
			[22] = { texture = 'beach-tr', rotation = 0 }
		},
		[8] = {
			[8] = { texture = 'beach-lm', rotation = 0 },
			[9] = { texture = 'grass', rotation = 0 },
			[10] = { texture = 'grass', rotation = 0 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'grass', rotation = 0 },
			[17] = { texture = 'grass', rotation = 0 },
			[18] = { texture = 'beach-dn', rotation = 0 },
			[19] = { texture = 'beach-dn', rotation = -90 },
			[20] = { texture = 'grass', rotation = 0 },
			[21] = { texture = 'grass', rotation = 0 },
			[22] = { texture = 'beach-dn', rotation = 0 },
			[23] = { texture = 'beach-tr', rotation = 0 }
		},
		[9] = {
			[8] = { texture = 'beach-bl', rotation = 0 },
			[9] = { texture = 'beach-bm', rotation = 0 },
			[10] = { texture = 'beach-dn', rotation = 180 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'grass', rotation = 0 },
			[17] = { texture = 'grass', rotation = 0 },
			[18] = { texture = 'grass', rotation = 0 },
			[19] = { texture = 'grass', rotation = 0 },
			[20] = { texture = 'grass', rotation = 0 },
			[21] = { texture = 'grass', rotation = 0 },
			[22] = { texture = 'grass', rotation = 0 },
			[23] = { texture = 'beach-dn', rotation = 0 },
			[24] = { texture = 'beach-tr', rotation = 0 }
		},
		[10] = {
			[10] = { texture = 'beach-bl', rotation = 0 },
			[11] = { texture = 'beach-dn', rotation = 180 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'beach-dn', rotation = 90 },
			[15] = { texture = 'beach-bm', rotation = 0 },
			[16] = { texture = 'beach-bm', rotation = 0 },
			[17] = { texture = 'beach-dn', rotation = 180 },
			[18] = { texture = 'grass', rotation = 0 },
			[19] = { texture = 'grass', rotation = 0 },
			[20] = { texture = 'grass', rotation = 0 },
			[21] = { texture = 'grass', rotation = 0 },
			[22] = { texture = 'grass', rotation = 0 },
			[23] = { texture = 'grass', rotation = 0 },
			[24] = { texture = 'beach-rm', rotation = 0 }
		},
		[11] = {
			[10] = { texture = 'beach-tl', rotation = 0 },
			[11] = { texture = 'beach-dn', rotation = -90 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'beach-rm', rotation = 0 },
			[17] = { texture = 'beach-bl', rotation = 0 },
			[18] = { texture = 'beach-dn', rotation = 180 },
			[19] = { texture = 'grass', rotation = 0 },
			[20] = { texture = 'grass', rotation = 0 },
			[21] = { texture = 'grass', rotation = 0 },
			[22] = { texture = 'grass', rotation = 0 },
			[23] = { texture = 'grass', rotation = 0 },
			[24] = { texture = 'beach-rm', rotation = 0 }
		},
		[12] = {
			[6] = { texture = 'beach-tl', rotation = 0 },
			[7] = { texture = 'beach-tm', rotation = 0 },
			[8] = { texture = 'beach-tr', rotation = 0 },
			[9] = { texture = 'beach-tl', rotation = 0 },
			[10] = { texture = 'beach-dn', rotation = -90 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'beach-rm', rotation = 0 },
			[18] = { texture = 'beach-lm', rotation = 0 },
			[19] = { texture = 'grass', rotation = 0 },
			[20] = { texture = 'grass', rotation = 0 },
			[21] = { texture = 'grass', rotation = 0 },
			[22] = { texture = 'grass', rotation = 0 },
			[23] = { texture = 'grass', rotation = 0 },
			[24] = { texture = 'beach-rm', rotation = 0 }
		},
		[13] = {
			[6] = { texture = 'beach-lm', rotation = 0 },
			[7] = { texture = 'grass', rotation = 0 },
			[8] = { texture = 'beach-dn', rotation = 0 },
			[9] = { texture = 'beach-dn', rotation = -90 },
			[10] = { texture = 'grass', rotation = 0 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'beach-dn', rotation = 90 },
			[14] = { texture = 'beach-br', rotation = 0 },
			[17] = { texture = 'beach-tl', rotation = 0 },
			[18] = { texture = 'beach-dn', rotation = -90 },
			[19] = { texture = 'grass', rotation = 0 },
			[20] = { texture = 'grass', rotation = 0 },
			[21] = { texture = 'grass', rotation = 0 },
			[22] = { texture = 'grass', rotation = 0 },
			[23] = { texture = 'grass', rotation = 0 },
			[24] = { texture = 'beach-rm', rotation = 0 }
		},
		[14] = {
			[6] = { texture = 'beach-lm', rotation = 0 },
			[7] = { texture = 'grass', rotation = 0 },
			[8] = { texture = 'grass', rotation = 0 },
			[9] = { texture = 'grass', rotation = 0 },
			[10] = { texture = 'grass', rotation = 0 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'beach-rm', rotation = 0 },
			[16] = { texture = 'beach-tl', rotation = 0 },
			[17] = { texture = 'beach-dn', rotation = -90 },
			[18] = { texture = 'grass', rotation = 0 },
			[19] = { texture = 'grass', rotation = 0 },
			[20] = { texture = 'grass', rotation = 0 },
			[21] = { texture = 'grass', rotation = 0 },
			[22] = { texture = 'grass', rotation = 0 },
			[23] = { texture = 'grass', rotation = 0 },
			[24] = { texture = 'beach-rm', rotation = 0 },
		},
		[15] = {
			[6] = { texture = 'beach-lm', rotation = 0 },
			[7] = { texture = 'grass', rotation = 0 },
			[8] = { texture = 'grass', rotation = 0 },
			[9] = { texture = 'grass', rotation = 0 },
			[10] = { texture = 'grass', rotation = 0 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'beach-dn', rotation = 0 },
			[14] = { texture = 'beach-tr', rotation = 0 },
			[15] = { texture = 'beach-tl', rotation = 0 },
			[16] = { texture = 'beach-dn', rotation = -90 },
			[17] = { texture = 'grass', rotation = 0 },
			[18] = { texture = 'grass', rotation = 0 },
			[19] = { texture = 'grass', rotation = 0 },
			[20] = { texture = 'grass', rotation = 0 },
			[21] = { texture = 'grass', rotation = 0 },
			[22] = { texture = 'grass', rotation = 0 },
			[23] = { texture = 'beach-dn', rotation = 90 },
			[24] = { texture = 'beach-br', rotation = 0 },
		},
		[16] = {
			[6] = { texture = 'beach-lm', rotation = 0 },
			[7] = { texture = 'grass', rotation = 0 },
			[8] = { texture = 'grass', rotation = 0 },
			[9] = { texture = 'grass', rotation = 0 },
			[10] = { texture = 'grass', rotation = 0 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'beach-dn', rotation = 0 },
			[15] = { texture = 'beach-dn', rotation = -90 },
			[16] = { texture = 'grass', rotation = 0 },
			[17] = { texture = 'grass', rotation = 0 },
			[18] = { texture = 'grass', rotation = 0 },
			[19] = { texture = 'grass', rotation = 0 },
			[20] = { texture = 'beach-dn', rotation = 90 },
			[21] = { texture = 'beach-bm', rotation = 0 },
			[22] = { texture = 'beach-bm', rotation = 0 },
			[23] = { texture = 'beach-br', rotation = 0 },
		},
		[17] = {
			[6] = { texture = 'beach-lm', rotation = 0 },
			[7] = { texture = 'grass', rotation = 0 },
			[8] = { texture = 'grass', rotation = 0 },
			[9] = { texture = 'grass', rotation = 0 },
			[10] = { texture = 'grass', rotation = 0 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'grass', rotation = 0 },
			[17] = { texture = 'grass', rotation = 0 },
			[18] = { texture = 'grass', rotation = 0 },
			[19] = { texture = 'beach-dn', rotation = 90 },
			[20] = { texture = 'beach-br', rotation = 0 }
		},
		[18] = {
			[6] = { texture = 'beach-bl', rotation = 0 },
			[7] = { texture = 'beach-dn', rotation = 180 },
			[8] = { texture = 'grass', rotation = 0 },
			[9] = { texture = 'grass', rotation = 0 },
			[10] = { texture = 'grass', rotation = 0 },
			[11] = { texture = 'grass', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'grass', rotation = 0 },
			[17] = { texture = 'grass', rotation = 0 },
			[18] = { texture = 'beach-dn', rotation = 90 },
			[19] = { texture = 'beach-br', rotation = 0 }
		},
		[19] = {
			[7] = { texture = 'beach-bl', rotation = 0 },
			[8] = { texture = 'beach-bm', rotation = 0 },
			[9] = { texture = 'beach-bm', rotation = 0 },
			[10] = { texture = 'beach-bm', rotation = 0 },
			[11] = { texture = 'beach-dn', rotation = 180 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'grass', rotation = 0 },
			[17] = { texture = 'beach-dn', rotation = 90 },
			[18] = { texture = 'beach-br', rotation = 0 }
		},
		[20] = {
			[11] = { texture = 'beach-bl', rotation = 0 },
			[12] = { texture = 'beach-dn', rotation = 180 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'beach-dn', rotation = 90 },
			[17] = { texture = 'beach-br', rotation = 0 }
		},
		[21] = {
			[12] = { texture = 'beach-lm', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'beach-rm', rotation = 0 }
		},
		[22] = {
			[11] = { texture = 'beach-tl', rotation = 0 },
			[12] = { texture = 'beach-dn', rotation = -90 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'beach-dn', rotation = 0 },
			[17] = { texture = 'beach-tr', rotation = 0 }
		},
		[23] = {
			[11] = { texture = 'beach-lm', rotation = 0 },
			[12] = { texture = 'grass', rotation = 0 },
			[13] = { texture = 'grass', rotation = 0 },
			[14] = { texture = 'grass', rotation = 0 },
			[15] = { texture = 'grass', rotation = 0 },
			[16] = { texture = 'grass', rotation = 0 },
			[17] = { texture = 'beach-rm', rotation = 0 }
		},
		[24] = {
			[11] = { texture = 'beach-bl', rotation = 0 },
			[12] = { texture = 'beach-bm', rotation = 0 },
			[13] = { texture = 'beach-bm', rotation = 0 },
			[14] = { texture = 'beach-bm', rotation = 0 },
			[15] = { texture = 'beach-bm', rotation = 0 },
			[16] = { texture = 'beach-bm', rotation = 0 },
			[17] = { texture = 'beach-br', rotation = 0 }
		}
	},
	walls = {
		{ x = 1280, y = 1536, rotation = 90 },
		{ x = 1280, y = 1856, rotation = 90 },
		{ x = 768, y = 2048, rotation = 0 },
		{ x = 1088, y = 2048, rotation = 0 },
		{ x = 1152, y = 943, rotation = 0 },
		{ x = 1472, y = 943, rotation = 0 },
		{ x = 1582, y = 751, rotation = 90 },
		{ x = 2642, y = 1071, rotation = 0 },
		{ x = 2642, y = 1664, rotation = 0 },
		{ x = 2560, y = 1152, rotation = 90 },
		{ x = 2560, y = 1472, rotation = 90 }
	},
	turrets = {
		{ x = 787, y = 2066, rotation = 0 },
		{ x = 881, y = 2066, rotation = 0 },
		{ x = 1107, y = 2066, rotation = 0 },
		{ x = 1201, y = 2066, rotation = 0 },
		{ x = 1292, y = 1561, rotation = -90 },
		{ x = 1292, y = 1656, rotation = -90 },
		{ x = 1292, y = 1882, rotation = -90 },
		{ x = 1292, y = 1976, rotation = -90 },
		{ x = 1171, y = 961, rotation = 0 },
		{ x = 1265, y = 961, rotation = 0 },
		{ x = 1491, y = 961, rotation = 0 },
		{ x = 1585, y = 961, rotation = 0 },
		{ x = 1593, y = 777, rotation = -90 },
		{ x = 1593, y = 872, rotation = -90 },
		{ x = 2661, y = 1089, rotation = 0 },
		{ x = 2755, y = 1089, rotation = 0 },
		{ x = 2661, y = 1682, rotation = 0 },
		{ x = 2755, y = 1682, rotation = 0 },
		{ x = 2571, y = 1177, rotation = 90 },
		{ x = 2571, y = 1272, rotation = 90 },
		{ x = 2571, y = 1497, rotation = 90 },
		{ x = 2571, y = 1592, rotation = 90 }
	},
	bases = {
		{ x = 1098, y = 782 },
		{ x = 974, y = 1742 },
		{ x = 2766, y = 1358 }
	}
}